### ISSUE TITLE
Add vulnerability policy sync in frontend

### ISSUE THREAD

**Issue by sahibamittal** [DependencyTrack/hyades#1009]
Add policy sync button under Vulnerability Policy model, which should request workflow steps for the hardcoded workflow token.

  * Should return 0..1 step, never more.
  * Step holds the current status (successful, in progress, failed, etc.).
  * If the step has failure info, display it.

**Comment by nscuro** [comment]
Closing as it was implemented in https://github.com/sahibamittal/dependency-track-frontend-upstream/pull/25, thanks @sahibamittal!
