### ISSUE TITLE
Replace custom `vers` handling with versatile

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#1092]
While implementing the vulnerability mirroring capability, we wrote our own `vers` code to deal with version ranges.

Custom code currently exists in the following places:

* API server
  * https://github.com/DependencyTrack/hyades-apiserver/tree/main/src/main/java/org/dependencytrack/parser/vers
  * https://github.com/DependencyTrack/hyades-apiserver/blob/main/src/main/java/org/dependencytrack/event/kafka/streams/processor/MirrorVulnerabilityProcessor.java
* mirror-service
  * https://github.com/DependencyTrack/hyades/blob/3b3b024ab2a7f18a627ba093771385b94af8c3c4/mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/osv/OsvToCyclonedxParser.java
  * https://github.com/DependencyTrack/hyades/blob/3b3b024ab2a7f18a627ba093771385b94af8c3c4/mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
  * https://github.com/DependencyTrack/hyades/blob/3b3b024ab2a7f18a627ba093771385b94af8c3c4/mirror-service/src/main/java/org/dependencytrack/vulnmirror/datasource/github/GitHubAdvisoryToCdxParser.java

Replace the custom `vers` handling with [versatile](https://github.com/nscuro/versatile).

versatile comes with utilities to convert GHSA and OSV ranges:

* https://github.com/nscuro/versatile/blob/c63483ff41778b904bc6ddf76fefe8e437d25ef5/src/main/java/io/github/nscuro/versatile/VersUtils.java#L33-L71
* https://github.com/nscuro/versatile/blob/c63483ff41778b904bc6ddf76fefe8e437d25ef5/src/main/java/io/github/nscuro/versatile/VersUtils.java#L73-L118

**Comment by sahibamittal** [comment]
Blocked due to below two issues : 

- [ ] [Add the splitting of vers range with more than 2 events](https://github.com/DependencyTrack/hyades/issues/1107)
- [ ] [Add vers range building for NVD vulnerabilities](https://github.com/DependencyTrack/hyades/issues/1108)
