### ISSUE TITLE
Setup GitHub issue and PR templates

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#1175]
To have more structure for issues and PRs, setup templates for them.

The `dependency-track` repository already has those, we can draw inspiration from there:

* https://github.com/DependencyTrack/dependency-track/tree/master/.github/ISSUE_TEMPLATE
* https://github.com/DependencyTrack/dependency-track/blob/master/.github/PULL_REQUEST_TEMPLATE.md

> [!NOTE]
> Issue templates are only needed for *this* repository, whereas PR templates will be needed for all involved repositories.

**Comment by sahibamittal** [comment]
PR templates already used in Hyades-apiserver and Hyades-frontend.
