### ISSUE TITLE
Port changes from upstream DT release 4.11.x

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#1190]
### Current Behavior

v4.11 of vanilla Dependency-Track is about to be released. We need to port the relevant changes to Hyades.

For reference, changes from v4.10.x were ported here: https://github.com/DependencyTrack/hyades/issues/983

### Proposed Behavior

API server: 

* v4.11.0: https://github.com/DependencyTrack/dependency-track/milestone/26?closed=1
* v4.11.1: https://github.com/DependencyTrack/dependency-track/milestone/37?closed=1
* v4.11.2: https://github.com/DependencyTrack/dependency-track/milestone/39?closed=1
* v4.11.3: https://github.com/DependencyTrack/dependency-track/milestone/40?closed=1
* v4.11.4: https://github.com/DependencyTrack/dependency-track/milestone/41?closed=1

Frontend:

* v4.11.0: https://github.com/DependencyTrack/frontend/milestone/18?closed=1
* v4.11.1: https://github.com/DependencyTrack/frontend/milestone/22?closed=1
* v4.11.2: https://github.com/DependencyTrack/frontend/milestone/24?closed=1
* v4.11.3: https://github.com/DependencyTrack/frontend/milestone/25?closed=1
* v4.11.4: https://github.com/DependencyTrack/frontend/milestone/26?closed=1

> [!NOTE]
> We decided to rebase our frontend changes on top of the frontend release v4.11.3, instead of porting individual PRs. v4.11.x came with lots of changes in code formatting, making the porting effort painful. Our frontend changes are very limited so far, making a rebase the easiest way forward.

| Issue / PR | Type | Description | Backported | Backport PR |
|:--------|:----------|:-------|:-------|:--------|
| https://github.com/DependencyTrack/dependency-track/pull/2472 | Enhancement | Global Audit View: Vulnerabilities | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/723 |
| https://github.com/DependencyTrack/dependency-track/pull/3248 | Bugfix | Project cloning logic for cloning policy violations and Violationanalysis | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/691 |
| https://github.com/DependencyTrack/dependency-track/pull/3259 | Enhancement | Trivy integration | TODO via https://github.com/DependencyTrack/hyades/issues/1343 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3260 | Enhancement | Return processing token when cloning project | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/659 |
| https://github.com/DependencyTrack/dependency-track/pull/3261 | Enhancement | ACL: Add projects to team should only show not yet added projects | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/689 |
| https://github.com/DependencyTrack/dependency-track/pull/3275 | Enhancement | Webhook alert token and new user alerts | ✅ | https://github.com/DependencyTrack/hyades/pull/1338, https://github.com/DependencyTrack/hyades-apiserver/pull/742 |
| https://github.com/DependencyTrack/dependency-track/pull/3284 | Enhancement | Preprocess CWE dictionary | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/688 |
| https://github.com/DependencyTrack/dependency-track/pull/3285 | Enhancement | Add "Show in Dependency-Graph" Button in "Affected Projects" List | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/671 |
| https://github.com/DependencyTrack/dependency-track/pull/3304 | Bugfix | Fix dropping of CWE table failing due to FK constraint | ❌ N/A, constraint was never created for Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3305 | Bugfix | Fix notifications not being sent for child projects where active is null | ❌ Already fixed | - |
| https://github.com/DependencyTrack/dependency-track/pull/3313 | Bugfix | Improve Error handling and add default version type | ❌ Already fixed | - |
| https://github.com/DependencyTrack/dependency-track/pull/3322 | Bugfix | Fix NVD API's last modified timestamp requiring restart to be applied | ❌ N/A, Hyades stores the timestamp differently | - |
| https://github.com/DependencyTrack/dependency-track/pull/3357 | Enhancement | Refactor BOM upload processing for better efficiency, correctness, and consistency | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/705 |
| https://github.com/DependencyTrack/dependency-track/pull/3368 | Enhancement | Update SPDX license list to v3.22 | ❌ N/A, was superseded by https://github.com/DependencyTrack/dependency-track/pull/3508 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3394 | Bugfix | Ignore withdrawn Github advisories | ✅ | https://github.com/DependencyTrack/hyades/pull/1305 |
| https://github.com/DependencyTrack/dependency-track/pull/3408 | Enhancement | Store computed severities in the database | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/706 |
| https://github.com/DependencyTrack/dependency-track/pull/3422 | Enhancement | Configurable email subject prefix | ✅ | https://github.com/DependencyTrack/hyades/pull/1307 |
| https://github.com/DependencyTrack/dependency-track/pull/3425 | Enhancement | enhance API to support frontend changes for active/inactive affected projects | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/701 |
| https://github.com/DependencyTrack/dependency-track/pull/3437 | Bugfix | https://github.com/DependencyTrack/dependency-track/pull/3437 | ❌ N/A, VulnDB is not yet supported in Hyades, see #286 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3456 | Bugfix | Fix URISyntaxException when NPM PURL contains special characters | ✅ | https://github.com/DependencyTrack/hyades/pull/1309 |
| https://github.com/DependencyTrack/dependency-track/pull/3488 | Bugfix | Finding Attributed On date is not retained when cloning projects | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/700 |
| https://github.com/DependencyTrack/dependency-track/pull/3491 | Enhancement | Bump CWE dictionary to v4.13 | ✅  | https://github.com/DependencyTrack/hyades/pull/1322 <br/>https://github.com/DependencyTrack/hyades-apiserver/pull/713 |
| https://github.com/DependencyTrack/dependency-track/pull/3492 | Enhancement | Apply consistent formatting to SQL queries; Use text blocks instead of string concatenation | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/709 |
| https://github.com/DependencyTrack/dependency-track/pull/3493 | Enhancement | Improve test coverage of Trivy integration | TODO via https://github.com/DependencyTrack/hyades/issues/1343 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3494 | Enhancement | Align retry configuration and behavior across analyzers | ❌ N/A, retry configs never deviated that much in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3499 | Enhancement | Add support for component properties | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/712 |
| https://github.com/DependencyTrack/dependency-track/pull/3502 | Enhancement | Add auto-generated changelog to GitHub releases | ❌ N/A, already done for Hyades repos | - |
| https://github.com/DependencyTrack/dependency-track/pull/3508 | Enhancement | Bump SPDX license list to v3.23 | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/714 |
| https://github.com/DependencyTrack/dependency-track/pull/3511 | Enhancement | adding cargo to IMetaAnalyzer | ✅ | https://github.com/DependencyTrack/hyades/pull/1242 |
| https://github.com/DependencyTrack/dependency-track/pull/3512 | Bugfix | Fix type of purl fields in Swagger docs | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/716 |
| https://github.com/DependencyTrack/dependency-track/pull/3514 | Enhancement | Report test coverage for all branches, not just master | ❌ N/A, already done with recent Codacy migration | - |
| https://github.com/DependencyTrack/dependency-track/pull/3517 | Enhancement | Upload test coverage for PRs via separate workflow | ❌ N/A, already done with recent Codacy migration | - |
| https://github.com/DependencyTrack/dependency-track/pull/3515 | Enhancement | Bump Alpine to 2.2.5 | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/628 |
| https://github.com/DependencyTrack/dependency-track/pull/3522 | Enhancement | Validate uploaded BOMs against CycloneDX schema | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/715 |
| https://github.com/DependencyTrack/dependency-track/pull/3535 | Enhancement | Improve Lucene observability | ❌ N/A, Lucene was removed in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3537 | Enhancement | Add endpoint for updating API key comment | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/702 |
| https://github.com/DependencyTrack/dependency-track/pull/3549 | Enhancement | Implement the hackage and nixpkgs meta analyzers | ✅ | https://github.com/DependencyTrack/hyades/pull/1332 |
| https://github.com/DependencyTrack/dependency-track/pull/3555 | Enhancement | Perform License Resolution On Name Field During SBOM Import | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/717 |
| https://github.com/DependencyTrack/dependency-track/pull/3556 | Bugfix | Update License Of Existing Components On BOM Upload | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/717 |
| https://github.com/DependencyTrack/dependency-track/pull/3557 | Enhancement | OpenAPI spec fixes and improvements | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/722 |
| https://github.com/DependencyTrack/dependency-track/pull/3558 | Bugfix | Provide meaningful error message for bom and vex exceeding Jackson's character limit | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/724 |
| https://github.com/DependencyTrack/dependency-track/pull/3559 | Bugfix | Fix unhandled NotFoundExceptions causing a HTTP 500 response | ❌ N/A, superseded by https://github.com/DependencyTrack/dependency-track/pull/3659 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3560 | Bugfix | Extend length of PURL and PURLCOORDINATES columns from 255 to 786 | ❌ N/A, alrady done in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3561 | Enhancement | Generate SARIF File Of Project Vulnerability Findings | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/746 |
| https://github.com/DependencyTrack/dependency-track/pull/3573 | N/A | Transfer copyright from Steve Springett to OWASP Foundation | ✅ | - |
| https://github.com/DependencyTrack/dependency-track/pull/3574 | Enhancement | Disable automatic API key generation for teams | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/725 |
| https://github.com/DependencyTrack/dependency-track/pull/3590 | Bugfix | Validate UUID request parameters | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/721 |
| https://github.com/DependencyTrack/dependency-track/pull/3588 | Enhancement | New feature: VulnDB Aliases! | ❌ N/A, VulnDB is not yet supported in Hyades, see #286 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3595 | Bugfix | Vuln db severity | ❌ N/A, VulnDB is not yet supported in Hyades, see #286 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3620 | Enhancement | Leverage component properties for Trivy scans | TODO via https://github.com/DependencyTrack/hyades/issues/1343 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3621 | Enhancement | support for experimental configurations | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/715 |
| https://github.com/DependencyTrack/dependency-track/pull/3625 | Enhancement | Include pagination parameters in OpenAPI spec | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/720 |
| https://github.com/DependencyTrack/dependency-track/pull/3630 | Enhancement | Trivy tweaks | TODO via https://github.com/DependencyTrack/hyades/issues/1343 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3631 | Enhancement | Include sorting query parameters in OpenAPI spec | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/743 |
| https://github.com/DependencyTrack/dependency-track/pull/3648 | Enhancement | Gracefully handle unique constraint violations | ❌ N/A, areas where this could happen either no longer exist in Hyades, or already deal with constraint violations (i.e. via retry) | - |
| https://github.com/DependencyTrack/dependency-track/pull/3650 | Bugfix | Fix JDOFatalUserException for long reference URLs from OSS Index | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/747 |
| https://github.com/DependencyTrack/dependency-track/pull/3651 | Enhancement | Log debug information upon possible secret key corruption | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/750 |
| https://github.com/DependencyTrack/dependency-track/pull/3652 | Enhancement | Bump Temurin base image to 21.0.3_9 | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/666 |
| https://github.com/DependencyTrack/dependency-track/pull/3657 | Enhancement | Add support for worker pool drain timeout | ❌ N/A, already implemented in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3659 | Bugfix | Catch all unhandled ClientErrorExceptions | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/744 |
| https://github.com/DependencyTrack/dependency-track/pull/3661 | Enhancement | Fall back to no authentication when OSS Index API token decryption fails | ❌ N/A, the token is currently provided via environment variable, no decryption is involved. | - |
| https://github.com/DependencyTrack/dependency-track/pull/3662 | Enhancement | Truncate ComponentProperty value at 1024 characters | @sahibamittal | https://github.com/DependencyTrack/hyades-apiserver/pull/748 |
| https://github.com/DependencyTrack/dependency-track/pull/3664 | Bugfix | Fix unique constraint violation during NVD mirroring via feed files | ❌ N/A, Hyades doesn't mirror the NVD via feed files | - |
| https://github.com/DependencyTrack/dependency-track/pull/3666 | Enhancement | Add the project name and project URL to bom processing notifications | ✅ | https://github.com/DependencyTrack/hyades/pull/1342 <br/> https://github.com/DependencyTrack/hyades-apiserver/pull/745 |
| https://github.com/DependencyTrack/dependency-track/pull/3667 | Bugfix | De-duplicate CPEs in NVD feed file parsing | ❌ N/A, Hyades doesn't mirror the NVD via feed files | - |
| https://github.com/DependencyTrack/dependency-track/pull/3672 | Enhancement | Run builds and CI on feature-* branches | ❌ N/A, already done | - |
| https://github.com/DependencyTrack/dependency-track/pull/3676 | Enhancement | Simplify BomUploadProcessingTaskTest | ❌ N/A, simplified code never existed in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3677 | Enhancement | Disable Maven transfer progress in CI | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/726 |
| https://github.com/DependencyTrack/dependency-track/pull/3678 | Bugfix | Fix missing default repos for Hackage and Nixpkgs | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/729 |
| https://github.com/DependencyTrack/dependency-track/pull/3680 | Enhancement | Reduce verbosity of ResourceTests | ✅ | https://github.com/DependencyTrack/hyades/issues/1190 |
| https://github.com/DependencyTrack/dependency-track/pull/3681 | Enhancement | Bump bundled frontend to v4.11.0 | ❌ N/A, frontend is no longer bundled in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3698 | Bugfix | Fix failing JSON BOM validation when specVersion is not one of the first fields | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/715 |
| https://github.com/DependencyTrack/dependency-track/pull/3701 | Bugfix | Fix broken global vuln audit view for MSSQL | ❌ N/A, MSSQL is no longer supported | - |
| https://github.com/DependencyTrack/dependency-track/pull/3729 | Bugfix | fix os handling when trivy sets pkgType on properties | TODO via https://github.com/DependencyTrack/hyades/issues/1343 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3785 | Bugfix | Handle breaking change in Trivy server API | TODO via https://github.com/DependencyTrack/hyades/issues/1343 | - |
| https://github.com/DependencyTrack/dependency-track/pull/3787 | Bugfix | Fix project name not showing in Jira tickets | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/703 |
| https://github.com/DependencyTrack/dependency-track/pull/3788 | Bugfix | Add date format to support offset in NuGet timestamps | ✅ | - |
| https://github.com/DependencyTrack/dependency-track/pull/3786 | Bugfix | Fix licenses not being resolved by name | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/705 |
| https://github.com/DependencyTrack/dependency-track/pull/3792 | Bugfix | Fix Slack notifications failing when no base URL is configured | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/703 |
| https://github.com/DependencyTrack/dependency-track/pull/3794 | Enhancement | Bump bundled frontend to 4.11.2 | ❌ N/A, frontend is no longer bundled in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3801 | Bugfix | Fix JDODataStoreException for unresolved licenses during BOM upload processing | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/705 |
| https://github.com/DependencyTrack/dependency-track/pull/3863 | Enhancement | Support ingestion of CycloneDX v1.6 BOMs | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/754 |
| https://github.com/DependencyTrack/dependency-track/pull/3864 | Bugfix | Fix inverted "show inactive" filter in vulnerability audit view | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/723 |
| https://github.com/DependencyTrack/dependency-track/pull/3866 | Bugfix | Fix BOM validation failing when URL contains encoded `[` and `]` characters | ✅  | https://github.com/DependencyTrack/hyades-apiserver/pull/755 |
| https://github.com/DependencyTrack/dependency-track/pull/3867 | Bugfix | Fix external references not being updated via POST /v1/component | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/697 |
| https://github.com/DependencyTrack/dependency-track/pull/3871 | Bugfix | Prevent XXE injection during CycloneDX validation and parsing | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/756 |
| https://github.com/DependencyTrack/frontend/pull/917 | Enhancement | Improve German translation | ✅ | https://github.com/DependencyTrack/hyades-frontend/pull/72 |
| https://github.com/DependencyTrack/frontend/pull/918 | Enhancement | Improve Chinese translation | ✅ | https://github.com/DependencyTrack/hyades-frontend/pull/79 |

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/main/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/hyades/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Labeled as good first issue since it's easy to pick individual changes. The expectation is not that all changes are ported in one go.

Essentially, pick a change from v4.11, and port only that change. I am happy to suggest tickets to port, and provide guidance on the implementation if folks are interested and not sure where to start.

**Comment by leec94** [comment]
hi i'm interested in working on this, feel free to assign me

**Comment by leec94** [comment]
https://github.com/DependencyTrack/hyades/pull/1051 

this PR ported issues from 4.11 to 4.10.x, so they already exist in hyades

these are the 4.11 issues that are already ported
- https://github.com/DependencyTrack/dependency-track/pull/3305
- https://github.com/DependencyTrack/dependency-track/pull/3313

**Comment by nscuro** [comment]
Thanks @leec94, I updated the table in the issue accordingly!

**Comment by nscuro** [comment]
Extracted Trivy support into separate issue since it'll be a larger task: https://github.com/DependencyTrack/hyades/issues/1343
