### ISSUE TITLE
End point that wraps the cloning of project and uploads sbom

### ISSUE THREAD

**Issue by VithikaS** [DependencyTrack/hyades#1265]
### Current Behavior

Currently, there is no option to upload sbom with cloning project. 
Project is cloned based on version and project name. Following flags provide an option on what attributes of project are cloned

 - includeTags
 - includeProperties
 - includeDependencies
 - includeComponents
 - includeServices
 - includeAuditHistory
 - includeACL
 

### Proposed Behavior

There is proposed enhancement for state management with cloning a project under this issue https://github.com/DependencyTrack/hyades/issues/1256

 It would be nice to have an endpoint that wraps both cloning and uploading Sbom and let it get processed asynchronously

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/main/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/hyades/issues) for whether this enhancement was already requested

**Comment by sahibamittal** [comment]
Story no longer required, closing it.
