### ISSUE TITLE
Possible incorrect values in unit test

### ISSUE THREAD

**Issue by prabhu** [DependencyTrack/hyades#1294]
### Current Behavior

The unit test has `SCORE_METHOD_CVSSV3` instead of `SCORE_METHOD_CVSSV31`, but the vector starts with `CVSS:3.1`

https://github.com/DependencyTrack/hyades/blob/eaee8e7db95787dce7ded7e8ea72c5c076ea5527/mirror-service/src/test/java/org/dependencytrack/vulnmirror/datasource/osv/OsvMirrorTest.java#L267C46-L267C65

### Steps to Reproduce

See code.

### Expected Behavior

CVSSv31 must be used to represent the semantic changes in the standard, even though the numerical value will be the same compared to 3.0.

### Hyades Version

latest

### Repository Type

Hyades services

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/hyades/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Ha, good spot @prabhu! 

We recently [fixed](https://github.com/stevespringett/cvss-calculator/pull/90) CVSSv3.0 / CVSSv3.1 differentiation issues in the CVSS parser library we use. Seems like for OSV this needs further adjusting.

**Comment by nscuro** [comment]
Hm, appears to be due to OSV not differentiating between the two: https://ossf.github.io/osv-schema/#severitytype-field

Will need to look at the vector instead of blindly trusting their judgement.
