### ISSUE TITLE
Plan and perform load tests

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#136]
We need to ensure that the architecture and service implementations meet our performance and scalability requirements.

### Test Data

* Generating SBOMs for various popular Container Images with Trivy: https://github.com/DependencyTrack/hyades/blob/main/load-tests/fixtures/generate.sh
* Downloading public SBOMs from Maven Central: https://github.com/nscuro/cdx-central
  * Currently yields ~5100 SBOMs with >= 100 components each, across all artifact versions

### Execution

Uploading a pool of SBOMs to Dependency-Track: https://github.com/nscuro/dtbench

**Comment by nscuro** [comment]
As part of this issue, also compare with Vanilla DT 4.x.

**Comment by mehab** [comment]
An initial load test has been completed with upto 60000 projects and the related metrics can be added to this issue to share results.
