### ISSUE TITLE
Adding Teams column to Project Dashboard UI

### ISSUE THREAD

**Issue by jmayer-lm** [DependencyTrack/hyades#1435]
### Current Behavior

Hello, our team at Lockheed Martin has deployed and been playing with Hyades for a little bit (very cool product!) and we wanted to start a discussion on contributing back some Project Dashboard UI updates. Before opening a PR on your team, we wanted to make sure we weren't conflicting any of your future work / roadmap you all had in mind, in regards to the Project Dashboard UI.

### Proposed Behavior

By adding a “Teams” Column filter, users will be able add/remove Teams column from their project dashboard via the column drop-down menu and view every project associated with a specific team, via clicking the team badge.  Contributions were made to both the Frontend and Api Server. We modeled the behavior after the "Tags" behavior. "Teams" column is only populated for projects Portfolio Access Control is enabled/used. This enhancement has been implemented and tested.
Thanks for taking the time to consider this and look forward to discussing!

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/main/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/hyades/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Hey @jmayer-lm, this sounds interesting for sure!

I'm wondering how this "scales" though as more and more teams are granted access to a project. Especially when team names are long-ish, I'd imagine the column would become *very* crowded. Can you share examples / screenshots of how this would look like?

**Comment by nscuro** [comment]
In any case, please feel free to just raise any PRs you have. There's no conflict with any planned feature that I can think of.

**Comment by jmayer-lm** [comment]
Hey @nscuro, great! I will be raising them here shortly! As requested, I have provided the screenshots of project that can be accessed by five teams. Initially shows as two, and then can be expanded to show the rest. 
![TeamsColumnColapsed](https://github.com/user-attachments/assets/66f58e14-549c-4c19-b718-6b2986b73c12)
![TeamsColumnExpanded](https://github.com/user-attachments/assets/042b28cc-b268-4a67-9b33-c08ba5fa7ef9)
