### ISSUE TITLE
Enhance the efficiency of streams by implementing the timestamp extractor interface and defining the grace period for record

### ISSUE THREAD

**Issue by mehab** [DependencyTrack/hyades#287]
The windowing operations are driven by record timestamps, not by wall-clock time. In Kafka Streams, the earliest timestamp across all partitions is chosen first for processing, and Kafka Streams uses the TimeStampExtractor interface to get the timestamp from the current record.
By implementing the TimeStamp extractor interface and defining the grace period for all the records, we would be able to better manage the parallel operations being done by all the analyzers. By defining a grace period ( which is by default 24 hours in Kafka) we would be able to set when the streams stops waiting for out of order records and return the result of computation. 
My understanding is also that we do not need a 24 hour grace period for the results from analyzers.
Reference documentation [here](https://developer.confluent.io/learn-kafka/kafka-streams/windowing/).

**Comment by nscuro** [comment]
No longer relevant in the current implementation.
