### ISSUE TITLE
Re-implement policy evaluation in hyades API server

### ISSUE THREAD

**Issue by mehab** [DependencyTrack/hyades#341]
**Current Behavior**<br/>
Currently the dependency track application performs policy evaluation of components of a project after the Vulnerability analysis is complete for all the components of the project. This is also a sequential and heavy task if triggered for a potfolio. This means that policies are evaluated sequentially for every project and every component in the portfolio. Thus if there are 10 policies to go by, and 150 components in a project and 1000 projects in a portfolio, we can picture how long we are looping around the policy evaluation to complete. 
<br/>
**Proposed Change**
<br/>
To speed up the policy evaluation for project and portfolio levels, we could leverage the partitions on kafka topics in two ways to advantage us:

1. One component being evaluated for multiple policies at the same time. 
2. Multiple components for a given project being evaluated for a given policy
3. Mutliple projects being evaluated in parallel for a policy 

If a policy needs the most recent vulnerability info of a component then we can achieve this by triggering policy evaluation of a component right after the vulnerability analysis of the component is complete. This would still be faster updates on policy rather than waiting for vulnerability analysis of all components to complete before doing policy evaluation.

I will attach a diagram as well for further clarity

**Comment by mehab** [comment]
Per discussion it seems like the best fit is to keep the policy evaluation on the hyades api server side. We could make it multi threaded so that the response on UI is faster. But would need to gauge the impact on performance of the application in terms of db.

**Comment by nscuro** [comment]
@mehab Can we close this issue, as https://github.com/DependencyTrack/hyades-apiserver/pull/54 has been merged?

**Comment by mehab** [comment]
Yes we can :) Closing this issue !!
