### ISSUE TITLE
Achieve horizontal scalability of API server

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#375]
### Current Behavior

The API server is currently not horizontally scalable, for various reasons:

* Search indexes being read from and written to on local disk
* TaskExecutors for event subscribers consuming from an in-memory queue
  * Some of this has been offloaded to Kafka
* DataNucleus' L2 cache being in-memory
  * There are options available to use distributed caches, but perhaps disabling caches altogether is also an option
* Keys for secret encryption, and JWT signing and verification are stored on disk
  * Not really an issue; Can be replaced with k8s secrets and mounted at runtime
    * We already do this for the secret key

### Proposed Behavior

Ensure that the API server is horizontally scalable. It should be possible to run multiple *active*  instances of it in parallel.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
### Update DataNucleus L2 Cache

We have disabled the L2 cache in the majority of places where background processing is done. A caching mechanism that caches all objects written to the datastore does not scale, especially not under heavy load. Uploading 100 BOMs meant 100 projects and all of their components were stored in memory. Unless we want to expect users to provision VMs with >32GB of RAM, L2 caching is not an option. The costs outweigh the benefits here, even for single-node deployments.

The L2 cache should be disabled globally. A distributed cache is undesirable as it couples availability of the API server to yet another external system. We still have the option to enable it though, so if at some point we find we need it, it would be easy to integrate.

### Update on Lucene Search Indexes

The indexes are currently only used for the `/api/v1/search` endpoint, which is not called by the UI. It did not receive much love in the recent past and has limited use (https://github.com/DependencyTrack/dependency-track/issues/2310#issuecomment-1374896321). Potentially breaking the API for the sake of a better implementation would likely be OK.

A dedicated search engine like Solr or Elasticsearch would be great, but the danger of dual writes and all sorts of data inconsistencies will be quite high. Kafka may be able to help (keyword [CDC](https://www.redhat.com/en/topics/integration/what-is-change-data-capture)), but that again introduces lots of complexity as well.

**Comment by syalioune** [comment]
Great work folks ! Hard to catch up after so much time away from DT. 

I think you've made the right decisions regarding the lucene indexes : trying to maintain dual systems or propagating changes throughout Kafka would introduce more problems than it will resolve especially considering the benefits from this feature. If anything, for the future I would advise looking up solutions like [zombodb](https://www.zombodb.com/documentation/) where consistency between RDBMS and search engine is managed by the RDBMS itself. If only it was agnostic to Postgresql. 
Leveraging FTS capabilities of RDBMS would be better but requires expertise in fine-tuning indexes and stuff.

One question that spring into my mind and that always been bugging me with DT scheduled tasks : How would observability be managed (especially with an event based architecture) ?

- Historical view of executed tasks
- Status of each task execution and access to failure description if any
- Next execution time

**Comment by nscuro** [comment]
Thanks @syalioune! 

> One question that spring into my mind and that always been bugging me with DT scheduled tasks : How would observability be managed (especially with an event based architecture) ?
> 
> * Historical view of executed tasks
> * Status of each task execution and access to failure description if any
> * Next execution time

Agreed, this is a challenge. What I think would be required for addressing all of these points is some form of workflow engine that would orchestrate task executions based on events (like the Camunda / Zeebe platform we both know :p). 

However, I am not yet sold on implementing a fully-fledged workflow engine in DT, or even integrating a 3rd party one. 

For short- to mid-term, we came to the conclusion that keeping a high level state of workflows will be sufficient (see #664 for details). This is mostly required to support the CI/CD use case of uploading BOMs and waiting for their processing to complete.

We would love your feedback on that if you ever get the chance to look into it!

**Comment by syalioune** [comment]
> We would love your feedback on that if you ever get the chance to look into it!

I had sneek peak today and it looks awesome so far. Will look at it more deeply this weekend and provide more elaborate feedback 😉

**Comment by nscuro** [comment]
I'm going to close this issue. The API server has been running in a multi-replica setup in a production environment for almost two months now. The original ask of this issue is fulfilled.

This is not to say that work on this is done, certainly there are more than enough areas to improve on still.
