### ISSUE TITLE
Test deployment on OpenShift / CRC

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#379]
We need to make sure that the system can be run on OpenShift or OpenShift-compatible platforms.

For local testing, Red Hat provides [CRC](https://github.com/crc-org/crc).

**Comment by nscuro** [comment]
Note: Maybe there are linters for checking OpenShift compat. of Dockerfiles? That would make it easier to spot issues early, without requiring a CRC cluster.

**Comment by nscuro** [comment]
We already got the system running on Minikube, most parts should be the same for OpenShift.

**Comment by mehab** [comment]
Starting on this one

**Comment by mehab** [comment]
was able to do an initial deployment of vulnerability-analyzer, frontend and hyades-apiserver on openshift in dev environment together and perform an end to end test on it. Will also deploy mirror service using this in dev environment.
