### ISSUE TITLE
Create automated smoke tests for API server

### ISSUE THREAD

**Issue by mehab** [DependencyTrack/hyades#391]
Currently the hyades and hyades api server consisting of multiple modules need to be tested manually after startup to see if they are functional. This needs to be automated to assist in faster deployments and testing of features. It also could be part of the build checks in github so that if the test fails after a particular feature change/ upgrade then the particular change should not be merged

**Comment by nscuro** [comment]
I have a skeleton for end-to-end tests ready that should cover this issue: https://github.com/DependencyTrack/hyades/tree/e2e/e2e

It spins up all containers of the system (Postgres, Redpanda, API server, Hyades services) using [testcontainers](https://www.testcontainers.org/).

Here's an example test: https://github.com/DependencyTrack/hyades/blob/e2e/e2e/src/test/java/org/hyades/e2e/BomUploadProcessingTest.java
