### ISSUE TITLE
Rework mirror-service changes in apiserver

### ISSUE THREAD

**Issue by sahibamittal** [DependencyTrack/hyades#451]
Mirror-service is being reworked in Hyades. Corresponding changes need to be done in apiserver:

- Input topic for mirroring commands have changed; Previously multiple, now only one
- Parsing has to be changed to Protobuf
- Account for vulnerabilities from GitHub when parsing

**Subtask of** https://github.com/DependencyTrack/hyades/pull/447

**Comment by nscuro** [comment]
Implemented in https://github.com/DependencyTrack/hyades-apiserver/pull/74
