### ISSUE TITLE
Github Mirroring throwing http2 error

### ISSUE THREAD

**Issue by mehab** [DependencyTrack/hyades#475]
With the latest version of Jeremy's library, the gihub mirror is not working and throwing an http2 related error. This needs to be handled as a code patch on our side or another change in Jeremy's library. 
<img width="1288" alt="GithubMirrorError" src="https://user-images.githubusercontent.com/26340948/229743858-62119c98-7378-4b1c-bade-5453a49eec1c.png">

**Comment by VithikaS** [comment]
Tried following steps to reproduce but could not reproduce it:
   1. Started mirror service with following properties
      mirror.datasource.github.api-key=ghp_****************************
      mirror.datasource.github.base-url=
    
   2. Sent GITHUB command on dtrack.vulnerability.mirror.command topic
   
   Mirroring worked fine and got data on Vulnerability topic
   
   
<img width="1116" alt="Screenshot 2023-07-04 at 12 46 29" src="https://github.com/DependencyTrack/hyades/assets/122881935/75b6f43d-5e11-4a98-9dc2-51a45fb68ce4">

**Comment by VithikaS** [comment]
Closing this issue since it is not reproducible.
