### ISSUE TITLE
Policy evaluation can take too long and cause the consumer thread to be kicked out of the consumer group

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#529]
We're seeing Kafka Streams consumer threads occasionally getting kicked out of the consumer group due to policy evaluation taking too long:

```
consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll with max.poll.records.
```

Followed by:

```
Detected that the thread is being fenced. This implies that this thread missed a rebalance and dropped out of the consumer group. Will close out all assigned tasks and rejoin the consumer group.
```

Prior to this happening, we can see the average thread process latency skyrocketing to 15-30s, which is entirely too much. It should be <= 10ms.

**Comment by mehab** [comment]
Might be able to address this with https://github.com/DependencyTrack/hyades/issues/405

**Comment by nscuro** [comment]
Related PRs already merged:
* https://github.com/DependencyTrack/hyades-apiserver/pull/145
* https://github.com/DependencyTrack/hyades-apiserver/pull/147
