### ISSUE TITLE
Implement centralized scheduling for recurring tasks

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#553]
[Recurring tasks](https://docs.dependencytrack.org/getting-started/recurring-tasks/) are currently scheduled in every instance of the API server, in [`TaskScheduler`](https://github.com/DependencyTrack/hyades-apiserver/blob/main/src/main/java/org/dependencytrack/tasks/TaskScheduler.java), using simple [`Timer`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Timer.html)s behind the scenes.

We need to scale the API server to multiple instances (https://github.com/DependencyTrack/hyades/issues/375), but this will be problematic when every instance schedules redundant tasks. As per https://github.com/DependencyTrack/hyades/issues/375#issuecomment-1463920478, as a short- to mid-term solution, tasks should be triggerable via REST API endpoint.

Once the endpoints are available, tasks can be scheduled via [`CronJob`](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/). The `CronJob`s merely `curl` an API server endpoint to trigger tasks. Requests are made against the k8s service of the API server.

`CronJob` supports various settings for retry, backoff and timeouts. To leverage these functionalities, API endpoints must block as long as the respective task is running.

To prevent certain heavy tasks (e.g. portfolio metrics update) from being executed concurrently, a locking mechanism must be used. Usage of https://github.com/lukas-krecan/ShedLock should be investigated.

**Comment by nscuro** [comment]
There's a working implementation for locking the portfolio metrics update task. We'll get that merged and then create new issues for the remaining work. In the meantime the new implementation can be thoroughly tested on test environments.

**Comment by mehab** [comment]
**Remaining tasks**

- Use cron expression instead of fixed delay scheduling until kubernetes cron jobs are used. 
- Make sure end to end test are unaffected even with multiple instances of apiserver
- Should not lead to performance degradation overall

**Comment by mehab** [comment]
Currently under test and needs to be observed for a few days before confirming and closing the issue

**Comment by nscuro** [comment]
Implemented in:

* https://github.com/DependencyTrack/hyades-apiserver/pull/187
* https://github.com/DependencyTrack/hyades-apiserver/pull/222
* https://github.com/DependencyTrack/hyades-apiserver/pull/234

And tested for multiple days in a test environment. Singleton tasks are only ever executed by one instance.

Thanks @VithikaS! 🙌
