### ISSUE TITLE
Add notification for completed vulnerability analysis

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#573]
We currently have notifications for:

* `BOM_CONSUMED`: Triggered whenever a BOM has been parsed successfully
* `BOM_PROCESSED`: Triggered whenever a parsed BOM has been processed successfully
* `BOM_PROCESSING_FAILED`: Triggered whenever processing a BOM failed

Where "processing" a BOM is referring to ingesting its data into the API server's database. Processing does not include the various analysis tasks being kicked off after the ingestion.

For CI use cases, the API server will respond with a token (UUID) to BOM upload requests. This token can be used with the [`/api/v1/bom/token/<TOKEN>`](https://github.com/DependencyTrack/hyades-apiserver/blob/1e1a2190241c973b77c6f087e6a2e082bbc9999f/src/main/java/org/dependencytrack/resources/v1/BomResource.java#L338-L356) endpoint to check whether there is still a task (consumption, processing, analysis) being performed on that BOM. The endpoint simply returns `true` or `false`.

Users that want to wait for certain tasks (e.g. vulnerability analysis) to complete on their uploaded BOM are expected to regularly poll the API using the upload token. While this works for smaller workloads, it puts the API server under additional stress once many clients start polling it.

Additionally, for non-CI use cases, it forces clients to block other operations while they're polling for the status of their tokens. We could reduce the load of both API server and clients if we instead emitted a "vulnerability analysis completed" notification that clients can consume. 

Whether the vulnerability analysis of a project or component is complete is already known in the API server's Kafka Streams topology: https://github.com/DependencyTrack/hyades-apiserver/blob/1e1a2190241c973b77c6f087e6a2e082bbc9999f/src/main/java/org/dependencytrack/event/kafka/KafkaStreamsTopologyFactory.java#L79

We just need to define the desired payload, and branch off the `completedVulnScanStream` to produce the notification to a new topic.

**There should be an [e2e test](https://github.com/DependencyTrack/hyades/tree/main/e2e) to cover this functionality**

**Comment by mehab** [comment]
taking this up :)

**Comment by mehab** [comment]
working on the end to end test for this
