### ISSUE TITLE
Bug: Metrics calculation resulting in different totals with aliases enabled and disabled state for hyades

### ISSUE THREAD

**Issue by mehab** [DependencyTrack/hyades#592]
**Description**
In the current implementation of metrics calculation, when aliases are enabled for Snyk and OSV, the vulnerabilities count on the overview of project and also on the dashboard is different from (less than) the total audit vulnerabilities count for the same project. 
When aliases are disabled, the counts are the same in both the places. 
This seems to be a gap in the stored procedure used for the metrics calculation. 
**With alias disabled**
<img width="1337" alt="Screenshot 2023-06-06 at 12 27 06" src="https://github.com/DependencyTrack/hyades/assets/26340948/ae529feb-424e-46e3-9985-d38bd23455db">
**With alias enabled**
<img width="1090" alt="Screenshot 2023-06-06 at 12 35 04" src="https://github.com/DependencyTrack/hyades/assets/26340948/ce9b842a-09a6-4e1b-9ae9-a7743f732a7b">

**Comment by nscuro** [comment]
This is intended behavior when aliases are enabled. Metrics do not count the same vulnerability multiple times if they are aliasing each other.
