### ISSUE TITLE
Move OSV ecosystem config to backend

### ISSUE THREAD

**Issue by sahibamittal** [DependencyTrack/hyades#609]
Currently, list of ecosystems is dependent on frontend and can be moved to backend for more consistency and stability.

**Comment by nscuro** [comment]
Consideration: If the ecosystem configuration is moved to the mirror-service, it would require a re-deployment of that service when the ecosystem configuration is changed. This may not be desirable and is not really end-user friendly.

**Comment by sahibamittal** [comment]
Agreed, closing this issue.
