### ISSUE TITLE
Re-implement support for `NEW_VULNERABLE_DEPENDENCY` notifications

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#643]
We currently do not emit `NEW_VULNERABLE_DEPENDENCY` notifications, because the [processor responsible for handling `ScanResult` records](https://github.com/DependencyTrack/hyades-apiserver/blob/main/src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java) does not "know" which component is "new".

To re-implement this feature, we could enrich records produced to `dtrack.vuln-analysis.component` with a new header, e.g. `x-dtrack-is-new-component: (true|false)`. This header will be propagated to `dtrack.vuln-analysis.result` records received by the API server again.

`BomUploadProcessingTask` already has the knowledge of which component is new: 

https://github.com/DependencyTrack/hyades-apiserver/blob/afe74d8f89a57a0c1c1f373ede45abf2f25eb64e/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java#L163

**Comment by VithikaS** [comment]
PR merged for this issue https://github.com/DependencyTrack/hyades-apiserver/pull/217/files

**Comment by nscuro** [comment]
Thanks @VithikaS! 🙌
