### ISSUE TITLE
Revisit conversion from NVD CVE records to CycloneDX BOV

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#733]
Revisit the CVE parsing logic and compare with how it's done in Open Vulnerability Project (from which we use the library to fetch CVEs). Double-check to ensure we're capturing the data correctly. 

* https://github.com/DependencyTrack/hyades/blob/main/mirror-service/src/main/java/org/hyades/vulnmirror/datasource/nvd/NvdToCyclonedxParser.java
* https://github.com/jeremylong/Open-Vulnerability-Project/blob/4b824b094b6e1327da67907e24eae62515d1d53b/open-vulnerability-store/src/main/java/io/github/jeremylong/openvulnerability/VulnerabilityTransformer.java#L202-L316

**Comment by sahibamittal** [comment]
I can take this up 👍🏼
