### ISSUE TITLE
Port DT Release 4.9.0 changes to Hyades

### ISSUE THREAD

**Issue by VithikaS** [DependencyTrack/hyades#858]
Changelog for DT Release 4.9.0 https://docs.dependencytrack.org/changelog/
Release 4.9.0 changes have to be ported to hyades

| Issue / PR | Type | Description | Backported | Backport PR |
|:--------|:----------|:-------|:-------|:--------|
| https://github.com/DependencyTrack/dependency-track/pull/2817 | Misc | Fix GHA set-output deprecation warnings | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/361 |
| https://github.com/DependencyTrack/dependency-track/pull/2872 | Bugfix | Fix memory leak in policy evaluation | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/230 |
| https://github.com/DependencyTrack/dependency-track/pull/2873 | Bugfix | Fix memory leak issue in vex upload processing task | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/229 |
| https://github.com/DependencyTrack/dependency-track/pull/2769 | Enhancement | Custom licenses | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/364 |
|@VithikaS https://github.com/DependencyTrack/dependency-track/pull/3051 | Bugfix | Fix JsonIgnore having no effect on transient field | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/362 |
|@sahibamittal https://github.com/DependencyTrack/dependency-track/pull/3083, https://github.com/DependencyTrack/dependency-track/pull/2623 | Enhancement | Create endpoint to fetch many components and services | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/366 |
| https://github.com/DependencyTrack/dependency-track/issues/2423 | Enhancement | Separate policy evaluation into its own task | N/A, already implemented in Hyades | https://github.com/DependencyTrack/hyades-apiserver/pull/160 |
| https://github.com/DependencyTrack/dependency-track/pull/2581 | Enhancement | Added transient List of ProjectVersions and set Metrics in Project | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/367 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/3068 | Bugfix | Fix NPE when checking for project without version | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/365 |
|@sahibamittal https://github.com/DependencyTrack/dependency-track/pull/2568 | Enhancement | New option to only return outdated components and/or only direct dependencies in the ComponentResource | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/372 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/2911 | Enhancement | Upgrade the snyk api version | N/A version is in application properties  | - |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/2989 | Enhancement | Log warning when Vex cannot be applied | ✅  | https://github.com/DependencyTrack/hyades-apiserver/pull/368 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/3047 | Enhancement | Prefix apikey with odt_ | N/A Already ported to apiserver | https://github.com/DependencyTrack/hyades-apiserver/pull/327 |
| https://github.com/DependencyTrack/dependency-track/issues/2871 | Enhancement | CWE Catalogue Out of Date | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/369<br/>https://github.com/DependencyTrack/hyades/pull/859 |
|@VithikaS https://github.com/DependencyTrack/dependency-track/issues/2997 | Enhancement | Allow operator and violation state to be specified |  ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/371|
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/3006 | Enhancement | Update SPDX license list to v3.21 | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/375 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/2675 | Enhancement | Add Docker Compose files for simplified local testing | Only porting partially; Compose files now live in the hyades repo | https://github.com/DependencyTrack/hyades-apiserver/pull/370 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/2913 | Enhancement | Use IntelliJ standard directory for run configurations, and add project icon | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/370 |
|@VithikaS https://github.com/DependencyTrack/dependency-track/issues/2537 | Enhancement | New Version Distance Policy Evaluator | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/374 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/3070 | Bugfix | Fix false negatives in NVD CPE matching | ✅ | https://github.com/DependencyTrack/hyades/pull/861 |
| @sahibamittal https://github.com/DependencyTrack/dependency-track/issues/2859 | Misc | Add regression test for XML BOM parsing | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/372 |
| @sahibamittal https://github.com/DependencyTrack/dependency-track/issues/2788 | Bugfix | Fix VDR export containing non-vulnerable components | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/372 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/3095 | Bugfix | Fix invalid Mattermost notification template; Add more thorough publisher tests | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/384 |
|@VithikaS https://github.com/DependencyTrack/dependency-track/issues/2243 | Bugfix | Add extensive test suite for CPE matching logic | NA Implemented with porting of #3070  | - |
|@VithikaS https://github.com/DependencyTrack/dependency-track/issues/2878 | Bugfix | Fix VDR export erroneously containing non-vulnerable components |  NA Implemented already with porting of #2788 |  -  |
|@VithikaS https://github.com/DependencyTrack/dependency-track/issues/3067 | Bugfix | Fix VEX export erroneously containing dependency graph |  ✅   |https://github.com/DependencyTrack/hyades-apiserver/pull/381 |
|@VithikaS https://github.com/DependencyTrack/dependency-track/issues/2980 | Bugfix | Fix version distance policy being evaluated despite not being configured |   ✅   |https://github.com/DependencyTrack/hyades-apiserver/pull/382 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/2651 | Enhancement | Include Cloud SQL database connectors | ✅  | https://github.com/DependencyTrack/hyades-apiserver/pull/383<br/>https://github.com/DependencyTrack/hyades/pull/870 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/2967 | Bugfix | Fix AffectedComponent format for CPEs with version ranges | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/385 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/issues/2903 | Enhancement | Update Docker image to latest debian stable release | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/387 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/3071 | Enhancement | Update cyclonedx-core-java to 8.0.0 / Support Import of CycloneDX 1.5 BOMs | On hold, waiting for release of cyclonedx-core-java 8.0.2 | - |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/3069 | Enhancement | Bump temurin base image to 17.0.8.1_1 | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/387 |
| @VithikaS https://github.com/DependencyTrack/dependency-track/pull/2971 | Bugfix | Exclude xml-apis dependency / The package javax.xml.parsers is accessible from more than one module | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/387 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/2400 | Enhancement | Implement SPDX expressions | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/393 |
| @nscuro https://github.com/DependencyTrack/dependency-track/pull/2965 | Enhancement | SPDX expression support improvements | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/396 |

**Comment by nscuro** [comment]
Note: Two PRs related to fixing memory leaks were already backported:
* https://github.com/DependencyTrack/dependency-track/pull/2872
* https://github.com/DependencyTrack/dependency-track/pull/2873

Closing #660 as duplicate.

**Comment by nscuro** [comment]
All done!
