### ISSUE TITLE
Support for other msg queues like GCP pub/sub

### ISSUE THREAD

**Issue by NissesSenap** [DependencyTrack/hyades#905]
This is a rather naive question, but since I can't read Java I will just ask it.

Is it feasible to add support for other messages queues instead of Kafka, for example GCP pub/sub?

As mentioned in https://github.com/DependencyTrack/hyades/blob/main/WTF.md Kafka is supported in many cloud providers and SaaS solutions but sadly not all of them.

I'm not too keen on running my own Kafka instance, and I would prefer not using another cloud provider/SaaS solution then I already do.
So in addition to Kafka it would be great to add other queuing systems? 

I assume you have written some kind of abstraction on top of your Kafka client, like an interface/class. Would you be willing to accept PRs to add other clients and other messages queues, or do you feel that the kafka features are too integrated? 

I can't personally do it since I don't know Java, but I have programmers at my company that could take a look if you would be willing to consider it.

**Comment by nscuro** [comment]
Hey @NissesSenap, appreciate the question.

> I'm not too keen on running my own Kafka instance, and I would prefer not using another cloud provider/SaaS solution then I already do.

Is this a reservation against Kafka itself, or more so the desire to completely hand off everything infrastructure-related to your cloud provider (as in, you also wouldn't run RabbitMQ or NATS if that was a requirement)?

> I assume you have written some kind of abstraction on top of your Kafka client, like an interface/class. Would you be willing to accept PRs to add other clients and other messages queues, or do you feel that the kafka features are too integrated?

I'll preface this with saying that I don't have much experience with GCP PubSub.

In general, Hyades is not currently built in a way that allows for the messaging protocol to be changed. Fundamentally, we chose Kafka (or rather the Kafka API) [for its specific properties](https://github.com/DependencyTrack/hyades/blob/main/WTF.md#why-kafka), which are not available in other standards like [JMS](https://en.wikipedia.org/wiki/Jakarta_Messaging) or [AMQP](https://en.wikipedia.org/wiki/Advanced_Message_Queuing_Protocol), or Pub/Sub systems like GCP PubSub (AFAIK) or AWS SNS.

Additionally, messaging standards, and systems that do not implement any standard at all, can vastly differ in how they work. How messages are sent (individually, in batches), whether messages are durable, whether partitions are involved, how messages are delivered, and how they're acknowledged by clients. 

Trying to abstract all this away comes with a heavy penalty on optimizability. As soon as an abstraction layer is introduced that would work with *any* messaging system, we can no longer rely on the benefits Kafka and its ecosystem provides. Conversely, the same would be true if GCP PubSub provides features that Kafka doesn't support.

That all being said, if GCP PubSub is roughly compatible with how Kafka works, we may be able to build a *very* thin abstraction layer to support them both. If we're currently doing things with Kafka that could be refactored to work with both, that is also something we can do. If both technologies turn out to work too differently however, then I don't think it would be a worthwhile exercise.

**Comment by NissesSenap** [comment]
Hey @nscuro, thanks for your quick reply as always.
I have nothing against Kafka, it's a great piece of technology, but I know enough about Kafka to know that I don't feel comfortable to run it on my own for such centric solution as DT is without spending even more time than I already have to run Kafka in production.

After your answer, I did some more research.
And just as pointed out in the documentation there are a number of Kafka SaaS/IaaS/Self hosted options, my assumption was that some of these options would be very expensive and of course they can be depending on how big your DT setup is. But in general most companies will need rather small Kafka setups, and for example AWS MSK was much better priced then I expected.

Sadly, there is no out of the box option for **GCP** users (you can of course get stuff like Confluent Cloud through the GCP marketplace), but of the major cloud providers it's the only one that got this issue. So I **agree** with you, it's not worth adding the extra complexity by adding a generic abstraction layer + code maintenance of supporting multiple msg queues.

Just a note about kraft, it's getting closer and closer when it comes to feature parity with [zookeeper](https://www.confluent.io/blog/introducing-apache-kafka-3-6/), but It's still some way to go, and it will definitely make Kafka easier to run in production.

Strimzi supports [kraft](https://strimzi.io/blog/2023/09/11/kafka-node-pools-supporting-kraft/), but the setup isn't the smoothest, but my understanding is that Strimzi 1.0 is getting worked on and will be based on Kafka 4.0 and will greatly improve the way you configure Kafka with Strimzi.

Looking forward to Hyades getting merged in to the main project, keep up the great work.

**Comment by nscuro** [comment]
Thanks for the kind words @NissesSenap.

I just wanted to add that the space around Kafka is steadily evolving, which was part of why we felt relying on the Kafka API was a viable thing to do. We have had great experience with [Redpanda](https://redpanda.com/), which can comfortably run with few resources, and without external dependencies like ZooKeeper. Our test- and demo setup [restricts its memory to <= 512MB](https://github.com/DependencyTrack/hyades/blob/a2153f2c94e0efe583e42d41863b0255994b3291/docker-compose.yml#L155-L158). 

If DT is not mission critical to your business, it can even be viable to run a single Redpanda instance as normal `Deployment` or `StatefulSet` in your k8s cluster. Operators like Strimzi would be overkill for such use cases. Replication, HA etc. is good and all, but *many* DT users will not require it, and maybe that's the case for you too.

There are also projects like [WarpStream](https://www.warpstream.com/) which promise to be even more cloud-friendly.
