### ISSUE TITLE
Port changes from upstream DT release 4.10.x

### ISSUE THREAD

**Issue by VinodAnandan** [DependencyTrack/hyades#983]
API server:
* 4.10.0: https://github.com/DependencyTrack/dependency-track/milestone/25?closed=1
* 4.10.1: https://github.com/DependencyTrack/dependency-track/milestone/35?closed=1

Frontend:
* 4.10.0: https://github.com/DependencyTrack/frontend/milestone/16?closed=1

| Issue / PR | Type | Description | Backported | Backport PR |
|:--------|:----------|:-------|:-------|:--------|
| https://github.com/DependencyTrack/dependency-track/pull/3089 | Enhancement | Use Java 21 JRE in container images | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/572 |
| https://github.com/DependencyTrack/dependency-track/pull/3103 | CI | Pin digests of GitHub Actions | - | - |
| https://github.com/DependencyTrack/dependency-track/pull/3104 | CI | Use strict token permissions in GitHub Actions workflows | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/572 |
| https://github.com/DependencyTrack/dependency-track/pull/3118 | Enhancement | Remove CPE table and associated code | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/547 |
| https://github.com/DependencyTrack/dependency-track/pull/3116 | Enhancement | Improve efficiency of index operations | n/a, search indexes have been removed in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/issues/2987 | Bugfix | Cannot manually rebuild search index of more than one entity type at time | n/a, search indexes have been removed in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3154 | Enhancement | Add retry with exponential backoff for NVD feed downloads | n/a, NVD feeds are not used in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3172 | Bugfix | Fix trailing comma in default Slack publisher template | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/571 |
| https://github.com/DependencyTrack/dependency-track/pull/3173 | Enhancement | Add average event processing duration to Grafana dashboard | - | - |
| https://github.com/DependencyTrack/dependency-track/pull/3112 | Enhancement | Add support for github component sources | ✅ | https://github.com/DependencyTrack/hyades/pull/1032, https://github.com/DependencyTrack/hyades-apiserver/pull/539 |
| https://github.com/DependencyTrack/dependency-track/pull/3175 | Enhancement | Add support for mirroring of the NVD via API | n/a, already implemented in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3194 | Bugfix | Fix NPE when affected node in OSV does not define a package | ✅ | https://github.com/DependencyTrack/hyades/pull/1072 |
| https://github.com/DependencyTrack/dependency-track/pull/2876 | Enhancement | Support authentication for public / non-internal repositories | n/a, already implemented in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3198 | Bugfix | Fix NPE for BOM_PROCESSING_FAILED notifications when parsing of the BOM failed | ✅ | https://github.com/DependencyTrack/hyades/pull/1073 |
| https://github.com/DependencyTrack/dependency-track/pull/3209 | Bugfix | Fix false positives in CPE matching due to ambiguous vendor/product relations | ✅ | https://github.com/DependencyTrack/hyades/pull/1061 |
| https://github.com/DependencyTrack/dependency-track/pull/3211 | Enhancement | Improve logging for notification publishing | ✅ | https://github.com/DependencyTrack/hyades/pull/1026, https://github.com/DependencyTrack/hyades-apiserver/pull/536 |
| https://github.com/DependencyTrack/dependency-track/pull/3222 | Bugfix | Fix Massive deterioration of the Portfolio Vulnerability Analysis performance due to unnecessary increment in the amount of components to proceed | n/a, code no longer exists in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3228 | Bugfix | Fix failure to delete PolicyViolations when they have an audit trail | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/562 |
| https://github.com/DependencyTrack/dependency-track/pull/3232 | Bugfix | Fix teams not being assignable to alerts with custom email publishers | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/550 |
| https://github.com/DependencyTrack/dependency-track/pull/3233 | Bugfix | Fix erroneous warning log during VEX import | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/550 |
| https://github.com/DependencyTrack/dependency-track/pull/3244 | Bugfix | Added a default value for the Project active field if it is null | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/550 |
| https://github.com/DependencyTrack/dependency-track/pull/3245 | Bugfix | Tweak container health check to prevent wget zombie processes on slow hosts | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/550 |
| https://github.com/DependencyTrack/dependency-track/pull/3246 | Bugfix | Fix NPEs in GitHub repository metadata analyzer | ✅ | https://github.com/DependencyTrack/hyades/pull/1051 |
| https://github.com/DependencyTrack/dependency-track/issues/2737 | Enhancement | Add missing support for supplier and manufacturer | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/570 |
| https://github.com/DependencyTrack/dependency-track/pull/3247 | Bugfix | Add migration to populate new AUTHENTICATIONREQUIRED column | na, already done in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3306 | Bugfix | Backport: Fix notifications not being sent for child projects where active is null | ✅ | https://github.com/DependencyTrack/hyades/pull/1051 |
| https://github.com/DependencyTrack/dependency-track/pull/3308 | Bugfix | Backport: Fix NPE in VersionDistancePolicyEvaluator when project has no direct dependencies | na, NPE is handled by sql, will add a test | - |
| https://github.com/DependencyTrack/dependency-track/pull/3312 | Bugfix | Backport: Fix ClassCastException when updating an existing ProjectMetadata#authors field  | ✅ | https://github.com/DependencyTrack/hyades-apiserver/pull/592 |
| https://github.com/DependencyTrack/dependency-track/pull/3323 | Bugfix | Backport: Fix NVD API's last modified timestamp requiring restart to be applied | n/a, timestamp is stored differently in Hyades | - |
| https://github.com/DependencyTrack/dependency-track/pull/3315 | Bugfix | Backport: Improve Error handling and add default version type | ✅ | https://github.com/DependencyTrack/hyades/pull/1051

**Comment by nscuro** [comment]
Not anticipating this to be a big task. Main feature of 4.10 was support for the NVD REST API which Hyades already had for a long time.

**Comment by VinodAnandan** [comment]
I would like to work on https://github.com/DependencyTrack/dependency-track/pull/3089,  https://github.com/DependencyTrack/dependency-track/pull/3103, https://github.com/DependencyTrack/dependency-track/pull/3104 . I will try to complete them in the next 2 or 3 days.
