### ISSUE TITLE
Create `hyades-frontend` repository

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#986]
In order to support the new features introduced in Hyades, we had to make changes to the Dependency-Track frontend.

We do not have an official fork of the frontend repository yet, but we urgently need one.

1. Fork the `DependencyTrack/frontend` repository to `DependencyTrack/hyades-frontend`
2. Update the various [GitHub Actions workflows](https://github.com/DependencyTrack/frontend/tree/master/.github/workflows) to work with the new repository
3. Apply all changes we made so far again, on top of the forked repository

**Comment by sahibamittal** [comment]
https://github.com/DependencyTrack/hyades-frontend
